import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Montserrat } from "next/font/google";


const montserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "300", "400", "600"]
})



export const metadata: Metadata = {
  title: "Techathon",
  description: "Generated by Techathon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable}  antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
